FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar UV
RUN pip install --no-cache-dir uv

# Copiar arquivos de dependência
COPY pyproject.toml uv.lock ./

# Instalar dependências congeladas
RUN uv sync --frozen

# Copiar código da aplicação
COPY . .

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
